### ISSUE TITLE
Add git binary as a dependency

### ISSUE THREAD

**Issue by dos1701** [blackmesalab/fireguard#26]
We should add the git binary as a dependency to permit git clone on freshly installed machines

**Comment by crisidev** [comment]
Yes sir!

**Comment by dos1701** [comment]
I'll give it a shot, just struggling with cross-compilation on macOS

**Comment by dos1701** [comment]
Reopening because we need git also inside the container.

**Comment by dos1701** [comment]
Why executing the apt-get install inside the container?
Shouldn't we bake the required packages insite the image itself?

**Comment by crisidev** [comment]
Docker buildx cannot still build the multiarch images right if I run apt during build.. so this is a workaround. We need an issue for this.

**Comment by uovobw** [comment]
fixed in current master, will go to the releases (likely 0.0.8) once travis comes back from oblivion
